export const offenseTypes = [
  {
    id: 1,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 2,
    categoryId: 2,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 3,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 4,
    categoryId: 3,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 5,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 6,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 7,
    categoryId: 2,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 8,
    categoryId: 3,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 9,
    categoryId: 2,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 10,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 11,
    categoryId: 2,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 12,
    categoryId: 3,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 13,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 14,
    categoryId: 2,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 15,
    categoryId: 3,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 16,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 17,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 18,
    categoryId: 3,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 19,
    categoryId: 2,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 20,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 21,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 22,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 23,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 24,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 25,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 26,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 271,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 28,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 29,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 30,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 31,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 32,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 33,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 34,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 35,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 36,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 37,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 38,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 39,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 40,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 41,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 42,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 43,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 44,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 45,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 46,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 47,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 48,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 49,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 50,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 51,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 52,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 53,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 54,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 55,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 56,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 57,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 58,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 59,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 60,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 61,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 62,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
  {
    id: 63,
    categoryId: 1,
    name: "В зоне действия знака «Остановка запрещена",
    hidden: false,
    hidden_on_map: false,
    scenario: "video-comment",
    traffic_category: "Нарушение правил остановки ТС (знак 3.27)",
    forbirding_comment:
      "Вы находитесь вне зоны действия знака 3.27 или соответствующей разметки.",
    video_max_time: 0,
    message_before_start:
      "Убедитесь, что автомобиль находится в зоне действия знака 3.27 или соответствующей разметки.",
    meta: "",
    deny_outside_zone: false,
    color: "CD4B45",
    weight: 10,
  },
];
export const offenseCategories = [
  {
    id: 1,
    name: "Нарушение правил парковки",
  },
  {
    id: 2,
    name: "Нарушение порядка оплаты парковки",
  },
  {
    id: 3,
    name: "Проверка по реестру",
  },
];
